#!/usr/bin/env python

import rospy
import sys
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2

class changer():
	def __init__(self):
		self.sub = rospy.Subscriber("/usb_cam/image_raw", Image, self.callback, queue_size = 1)
		self.pub = rospy.Publisher("/bgr", Image, queue_size = 1)
	def callback(self, data):
		bridge = CvBridge()
		img = bridge.imgmsg_to_cv2(data, desired_encoding='passthrough')
		bgrimg = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
		cvimg = bridge.cv2_to_imgmsg(bgrimg, encoding="rgb8")
		self.pub.publish(cvimg)
	
rospy.init_node("converter")
ch = changer()
rospy.loginfo("run")
rospy.spin()



